apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
data:
  APP_ENV: "PROD"
  APP_VERSION: "v1.0.0"
  APP_COLOR: "#ef4444"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one
          image: app-one:2.0.0
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: app-one
  namespace: prod
spec:
  selector:
    app: app-one
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-one
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
    - host: app-one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-one
                port:
                  number: 80
